### ISSUE TITLE
update URLs for braingenomicssuperstruct

### ISSUE THREAD

**Issue by satra** [OpenNeuroLab/metasearch#10]
from 

/data/Projects/BrainGenomicsSuperstructProject/sub-1000/...

to 

/data/Projects/BrainGenomicsSuperstructProject/**orig_bids**/sub-1000/...

if the boto crawler is setup properly, this should update automatically.

**Comment by r03ert0** [comment]
are the braingenomicssuperstruct links publically available now? (the openfmri brains are going to be on amazon next week)

**Comment by satra** [comment]
@r03ert0 - yes at the location pointed to above - they are in metasearch as well but with improper urls - i've added a project with the proper urls on brainbox.

however, brainbox i can't check it seemed to have sent brainbox into a bit of a tailspin by adding 1500 brains.

**Comment by satra** [comment]
@nicholsn - participant id's should be zero-padded and be strings. i don't think they should be numeric.

**Comment by nicholsn** [comment]
@satra sounds good, will create a link as strings - some of the pheno csv files just list the ids as numeric

**Comment by satra** [comment]
i think pandas reads them as numeric, but you can force it via dtype

**Comment by nicholsn** [comment]
ok, thanks

**Comment by satra** [comment]
this is fixed.
