### ISSUE TITLE
page says 11045 rows, but provided csv seems to have only 8120

### ISSUE THREAD

**Issue by yarikoptic** [OpenNeuroLab/metasearch#14]
# What would you like to do:

- [x] Report an issue

## Report an issue

- Browser name and version: 
- OS/Platform name and version:

Version 63.0.3239.84 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by satra** [comment]
perhaps you are looking at the wrong file:

```bash
$ wget https://raw.githubusercontent.com/OpenNeuroLab/metasearch/master/docs/data/phenotype_mri.csv
--2018-02-20 15:10:01--  https://raw.githubusercontent.com/OpenNeuroLab/metasearch/master/docs/data/phenotype_mri.csv
Resolving raw.githubusercontent.com... 151.101.208.133
Connecting to raw.githubusercontent.com|151.101.208.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1661730 (1.6M) [text/plain]
Saving to: ‘phenotype_mri.csv’

phenotype_mri.csv       100%[============================>]   1.58M  1.42MB/s    in 1.1s    

2018-02-20 15:10:03 (1.42 MB/s) - ‘phenotype_mri.csv’ saved [1661730/1661730]

$ cat phenotype_mri.csv | wc -l
   11045
```

**Comment by yarikoptic** [comment]
yeah, we were trying to get it from the website itself. through that icon in the top right corner.
@kyleam please use https://raw.githubusercontent.com/OpenNeuroLab/metasearch/master/docs/data/phenotype_mri.csv

**Comment by satra** [comment]
ah the export restricts it to those rows that have a corresponding MRI scan.
