### ISSUE TITLE
csv ends in literal <br/>

### ISSUE THREAD

**Issue by kaczmarj** [OpenNeuroLab/metasearch#16]
Hello, I am trying to copy a csv of a subset of data from metasearch. The end of each line in the csv contains the string `<br/>`. Is this intended?

Here is a screenshot:
![image](https://user-images.githubusercontent.com/17690870/38142208-77f4a4b8-3409-11e8-834d-220e489c5020.png)

I'm guessing the line below produces this behavior.

https://github.com/OpenNeuroLab/metasearch/blob/845265ed415ff3b6a8a7d194ce24653b7a0cfdd6/docs/metasearch.js#L223

Thank you.

**Comment by satra** [comment]
thanks @kaczmarj
